### ISSUE TITLE
{css} { justabite }

### ISSUE THREAD

**Issue by nuoxoxo** [nuoxoxo/playground#25]
# navbar (./....)
```css
.navbar {
    /*height: 84px;
    background: white;
    padding: 0px 20px;*/
    box-shadow: -1.4px -1.4px 6px 0 #97a2a0;
}

.navbar .wrapper {
    height: 84px;
    background: white;
    display: flex;
    justify-content:space-between;
    align-items:center;
    padding: 0px 20px;
}

.navbar__site-name {
    font-family: Questrial;
    font-size: 36px;
    color: #489846
  }

.navbar__list {
    padding:0;
    margin:0;
    list-style:none;
    display:flex;
    font-size:18px;
}

.navbar__list li {
    text-align: center;
    margin-left: 12px;
    border-radius: 9px;
    transition: background 0.2s;
}

.navbar__list li.active, 
.navbar__list li:hover {
    background: #dd7286
}

.navbar__list li a {
    display: block;
    text-decoration: none;
    color: inherit;
    padding:12px 24px;
}

.navbar__list li.active a, 
.navbar__list li:hover a {
    color: white
}

.wrapper {
    max-width: 1024px;
    margin: 0 auto;
}

@media(max-width: 768px) {
    .navbar .wrapper {
        height: 120px;
        flex-direction:column;
        justify-content:space-between;
        padding:0px
    }

    .navbar__site-name {
        margin-top: 12px
    }

    .navbar__list {
        display: flex;
        width: 100%;
    }
    
    .navbar__list li {
        flex: 1;
        margin-left: 0;
        border-radius: 0;
    }
}
```
```css
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Just a Bite!</title>
    <link rel="stylesheet" href="https://necolas.github.io/normalize.css/8.0.1/normalize.css">
    <link href="./styles.css" rel="stylesheet">
    </link>
  </head>
  <body>
    <nav class="navbar">
      <div class="wrapper">
        <div class="navbar__site-name">
          Just a Bite!
        </div>
        <ul class="navbar__list">
          <li class="active"><a href="#">抽個大獎</a></li>
          <li><a href="#">我要點餐</a></li>
          <li><a href="#">查訊訂單</a></li>
          <li><a href="#">常見問題</a></li>
        </ul>
      </div>
    </nav>
  </body>
</html>
```
# banner wrapper images (../....)
```css
h2 {
    margin: 0
}

.navbar {
    box-shadow: -1.4px -1.4px 6px 0 #97a2a0;
}

.navbar .wrapper {
    height: 84px;
    background: white;
    display: flex;
    justify-content:space-between;
    align-items:center;
    padding: 0px 20px;
}

.navbar__site-name {
    font-family: Questrial;
    font-size: 36px;
    color: #489846
  }

.navbar__list {
    padding:0;
    margin:0;
    list-style:none;
    display:flex;
    font-size:18px;
}

.navbar__list li {
    text-align: center;
    margin-left: 12px;
    border-radius: 9px;
    transition: background 0.2s;
}

.navbar__list li.active, 
.navbar__list li:hover {
    background: #dd7286
}

.navbar__list li a {
    display: block;
    text-decoration: none;
    color: inherit;
    padding:12px 24px;
}

.navbar__list li.active a, 
.navbar__list li:hover a {
    color: white
}

.wrapper {
    max-width: 1024px;
    margin: 0 auto;
    padding: 0px 12px;
}

.banner {
    position: relative;
    height: 400px;
    background: url("img/2.jpg") center/cover no-repeat;
}

/* 偽元素 */

.banner:after {
    content: "";
    position: absolute; 
    /* abs 的定位是往上找第一個不是 static 的元素
    因此 .banner 應設為 relative 
    .banner h1 設為 relative && z-index: 2 */
    background: rgba(0,0,0,0.4);
    top: 0;
    bottom: 0;
    left: 0;
    right: 0
}

.banner h1 {
    display: inline-block;
    position: relative;
    color: white;
    font-weight: bold;
    font-size: 56px;
    margin: 0;
    z-index: 2;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%)
}

.section {
    text-align: center;
    margin-top: 80px
}

.section__title {
    display: inline-block;
    font-size: 36px;
    border-left: solid 15px #a3dea2;
     /* margin 是對外的 padding 是對內 */
     padding-left: 16px;
     margin-bottom: 36px;
}

.section__desc {
    font-size: 16px;
    line-height: 2em;
    /* em 就是 font size */
    /* rem 是針對 body 的 font size */
    margin: 0px 0px 68px 0px 
    /* margin: 上右下左 */
}

.button {
    display: inline-block;
    padding: 60px 80px;
    font-size: 36px;
    color: #3e613d;
    border-radius: 10%;
    cursor: pointer;
    transition: transform 0.1s;
}

.button:hover {
    transform: scale(1.2);
}

.btn-order {
    background: #a8e8e1;
}

.btn-query {
    margin-left: 23px;
    background: #f9f9b5;
}

.section__images{
    display:flex;
}

/*.four_samples {
    width: 25%
}*/

.section__images div {
    width: 25%;
}

.section__images img {
    width: 100%;
}

@media(max-width: 768px) {
    .navbar .wrapper {
        height: 120px;
        flex-direction:column;
        justify-content:space-between;
        padding:0px
    }

    .navbar__site-name {
        margin-top: 12px
    }

    .navbar__list {
        display: flex;
        width: 100%;
    }
    
    .navbar__list li {
        flex: 1;
        margin-left: 0;
        border-radius: 0;
    }

    .banner {
        height: 300px
    }

    .btn-query {
        margin-top: 16px;
        margin-left: 0
    }

    .section__images {
        flex-direction: column;
    }

    .section__images div {
        width: 100%;
    }
}
```
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Just a Bite!</title>
    <link rel="stylesheet" href="https://necolas.github.io/normalize.css/8.0.1/normalize.css">
    <link href="./styles.css" rel="stylesheet">
    </link>
  </head>
  <body>
    <nav class="navbar">
      <div class="wrapper">
        <div class="navbar__site-name">
          Just a Bite!
        </div>
        <ul class="navbar__list">
          <li class="active"><a href="#">抽個大獎</a></li>
          <li><a href="#">我要點餐</a></li>
          <li><a href="#">查詢訂單</a></li>
          <li><a href="#">常見問題</a></li>
        </ul>
      </div>
    </nav>
    <section class="banner">
      <h1>咬一口廚房</h1>
    </section>
    <div class="wrapper">
      <section class="section">
        <h2 class="section__title">
          當輕食之風盛起
        </h2>
        <p class="section__desc">由於現代人生活忙碌，常以外食為主，當高糖、高鹽、高油成為人們的日常，會導致慢性疾病與肥胖的機率大增
          <br>
          我們定期走訪農田，選用最天然、營養的食材，以簡單的烹調方式處理，最大化忠實呈現食材原本的鮮味
          <br>
          咬一口不只賣餐點，我們希望能夠讓大家愛上料理的魅力，餐館特意打造全開放式廚房，烹調透明化，也不定時舉辦美食廚房DIY，讓大家體驗不需要過多調味，就能擁有千變萬化的食物口感
      </p>
      <div class="buttons">
        <div class="button btn-order">我要點餐</div>
        <div class="button btn-query">查詢訂單</div>
      </div>
      </section>
      <section class="section">
        <h2 class="section__title">
          Menu 搶先看
        </h2>
        <div class="section__images">
          <!-- 
          <img src="img/f-001.png" class="four_samples">
          <img src="img/f-002.png" class="four_samples">
          <img src="img/f-003.png" class="four_samples">
          <img src="img/f-004.png" class="four_samples">
          -->
          <div><img src="img/f-001.png"></div>
          <div><img src="img/f-002.png"></div>
          <div><img src="img/f-003.png"></div>
          <div><img src="img/f-004.png"></div>
        </div>
      </section>
    </div>
  </body>
</html>
```
